Bazarkin/Sindika.Web/Models/GoodView.cs
using Bazarkin.ClassLibrary;
using Bazarkin.Domain;
using Sindika.Web.BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sindika.Web.Models
{
    public class GoodView
    {
        public Good good;
        public Manufacturer manufacturer;
        public List<ImageGood> imageGoodList;
        public List<ModificationAndPrice> modificationAndPriceSet;
        public List<PropertyGroupAndValue> propertyGroupAndValueSet;
        public List<OrganizationUnitAndPrice> organizationUnitAndPriceList;
        public BreadCrumbs breadCrumbs;

        public GoodView() { }

        public GoodView(EFDbContext db, List<ModificationGood> modificationGoodList, ModificationGood modificationGoodActive, Organization organization)
        {
            int goodId = modificationGoodList[0].Good.Id;
            good = db.GoodSet.Where(x => x.Id == goodId).FirstOrDefault();
            manufacturer = db.ManufacturerSet.Where(x => x.Id == good.Manufacturer.Id).FirstOrDefault();

            breadCrumbs = new BreadCrumbs(db, good);

            // Изображения

            if (modificationGoodActive == null)
            {
                imageGoodList = db.ImageGoodSet.Where(x => x.Good.Id == good.Id).ToList();
                if (imageGoodList != null)
                {
                    imageGoodList = imageGoodList.OrderBy(x => x.OrderIndex).ToList();
                }
            }
            else
            {
                List<ImageModificationGood> imageModificationGoodList = db.ImageModificationGoodSet.Where(x => x.ModificationGood.Id == modificationGoodActive.Id).ToList();

                if (imageModificationGoodList != null)
                {
                    imageGoodList = new List<ImageGood>();
                    foreach (var imageModificationGood in imageModificationGoodList)
                    {
                        imageGoodList.Add(db.ImageGoodSet.Where(x => x.Id == imageModificationGood.ImageGood.Id).FirstOrDefault());
                    }
                    imageGoodList = imageGoodList.OrderBy(x => x.OrderIndex).ToList();
                }
            }

            // Модификации и цены

            Dictionary<int, string> modificationNameDict = GoodLib.GetModificationNameDict(good);

            modificationAndPriceSet = new List<ModificationAndPrice>();
            foreach (var modificationGood in modificationGoodList)
            {
                modificationAndPriceSet.Add(new ModificationAndPrice(db, modificationGood, modificationNameDict.Where(x => x.Key == modificationGood.Id).FirstOrDefault().Value));
            }

            // Торговые точки и цены

            organizationUnitAndPriceList = new List<OrganizationUnitAndPrice>();            
            List<OrganizationUnit> organizationUnitList = new List<OrganizationUnit>();

            List<Price> priceList = new List<Price>();
            foreach (var modificationGood in modificationGoodList)
            {
                priceList.AddRange(db.PriceSet.Where(x => x.ModificationGood.Id == modificationGood.Id).ToList());
            }

            foreach (var price in priceList)
            {
                organizationUnitList.Add(db.OrganizationUnitSet.Where(x => x.Id == price.OrganizationUnit.Id).First());
            }
            organizationUnitList = organizationUnitList.Distinct().ToList();

            foreach (var organizationUnit in organizationUnitList)
            {
                organizationUnitAndPriceList.Add(new OrganizationUnitAndPrice(db, organizationUnit, modificationGoodList));
            }

            // Свойства и значения

            propertyGroupAndValueSet = new List<PropertyGroupAndValue>();
            List<PropertyValueGroup> propertyValueGroupSet = new List<PropertyValueGroup>();
            foreach (var modificationGood in modificationGoodList)
            {
                propertyValueGroupSet.AddRange(db.PropertyValueGroupSet.Where(x => x.ModificationGood.Id == modificationGood.Id));
            }
            List<PropertyGroup> propertyGroupList = new List<PropertyGroup>();
            foreach (var propertyValueGroup in propertyValueGroupSet)
            {
                propertyGroupList.Add(db.PropertyGroupSet.Where(x => x.Id == propertyValueGroup.Property.PropertyGroup.Id).FirstOrDefault());
            }
            propertyGroupList = propertyGroupList.Distinct().ToList();
            foreach (var propertyGroup in propertyGroupList)
            {
                propertyGroupAndValueSet.Add(new PropertyGroupAndValue(db, propertyGroup, propertyValueGroupSet, good));
            }
        }

        public class ModificationAndPrice
        {
            public ModificationGood modificationGood;
            public List<Price> priceSet;
            public string modificationString;

            public ModificationAndPrice() { }

            public ModificationAndPrice(EFDbContext db, ModificationGood modificationGood, string modificationString)
            {
                this.modificationGood = modificationGood;
                priceSet = db.PriceSet.Where(x => x.ModificationGood.Id == modificationGood.Id).ToList();

                this.modificationString = modificationString;
            }
        }

        public class PropertyGroupAndValue
        {
            public PropertyGroup propertyGroup;
            public List<PropertyAndValue> propertyAndValueSet;

            public PropertyGroupAndValue(EFDbContext db, PropertyGroup propertyGroup, List<PropertyValueGroup> propertyValueGroupSet, Good good)
            {
                this.propertyGroup = propertyGroup;

                Category category = db.CategorySet.Where(x => x.Id == good.Category.Id).FirstOrDefault();
                List<PropertyCategory> propertyCategoryList = db.PropertyCategorySet.Where(x => x.Category.Id == category.Id).ToList();

                List<Property> propertySet = new List<Property>();
                foreach(var propertyCategory in propertyCategoryList)
                {
                    Property property = db.PropertySet.Where(x => x.Id == propertyCategory.Property.Id && x.PropertyGroup.Id == propertyGroup.Id).FirstOrDefault();
                    if (property != null)
                    {
                        propertySet.Add(property);
                    }
                }
                propertySet = propertySet.OrderBy(x => x.Name).ToList();

                propertyAndValueSet = new List<PropertyAndValue>();
                foreach (var property in propertySet)
                {
                    propertyAndValueSet.Add(new PropertyAndValue(db, property, propertyValueGroupSet));
                }
            }
        }

        public class PropertyAndValue
        {
            public Property property;
            public string propertyValueString;

            public PropertyAndValue(EFDbContext db, Property property, List<PropertyValueGroup> propertyValueGroupSet)
            {
                this.property = property;
                this.propertyValueString = string.Empty;
                propertyValueGroupSet = propertyValueGroupSet.Where(x => x.PropertyValue.Property.Id == property.Id).ToList();
                List<PropertyValue> propertyValueSet = new List<PropertyValue>();
                foreach (var propertyValueGroup in propertyValueGroupSet)
                {
                    propertyValueSet.Add(db.PropertyValueSet.Where(x => x.Id == propertyValueGroup.PropertyValue.Id).FirstOrDefault());
                }
                propertyValueSet = propertyValueSet.Distinct().ToList();
                foreach (var propertyValue in propertyValueSet)
                {
                    if (propertyValueString != string.Empty)
                    {
                        propertyValueString += " | ";
                    }
                    propertyValueString += propertyValue.Value;
                }
            }
        }

        public class OrganizationUnitAndPrice
        {
            public Organization organization;
            public OrganizationUnit organizationUnit;
            public List<Price> priceSet;
            public string addressStr;

            public OrganizationUnitAndPrice() { }

            public OrganizationUnitAndPrice(EFDbContext db, OrganizationUnit organizationUnit, List<ModificationGood> modificationGoodSet)
            {
                this.organizationUnit = organizationUnit;
                organization = db.OrganizationSet.Where(x => x.Id == organizationUnit.Organization.Id).FirstOrDefault();
                priceSet = new List<Price>();

                foreach (var modificationGood in modificationGoodSet)
                {
                    Price price = db.PriceSet.Where(x => x.ModificationGood.Id == modificationGood.Id && x.OrganizationUnit.Id == organizationUnit.Id).FirstOrDefault();
                    if (price != null)
                    {
                        priceSet.Add(price);
                    }
                }

                ContactGroup cg = db.ContactGroupSet.Where(x => x.Id == organizationUnit.ContactGroup.Id).FirstOrDefault();
                Address address = db.AddressSet.Where(x => x.ContactGroup.Id == cg.Id).FirstOrDefault();
                addressStr = AddressLib.ObjectToString(address);
            }
        }
    }
}

Bazarkin/Sindika.Web/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sindika.Web.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            ViewBag.Title = String.Format("Синдика | Корзина");
            return View();
        }
    }
}

Bazarkin/Sindika.Web/Controllers/GoodController.cs
using Bazarkin.Domain;
using Sindika.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Bazarkin.Web.Controllers
{
    /// <summary>
    /// Страница товара
    /// </summary>
    public class GoodController : Controller
    {
        private EFDbContext db = new EFDbContext();

        [HttpGet]
        public ActionResult Index()
        {
            int goodId;
            if (RouteData.Values["goodId"] != null)
            {
                goodId = Convert.ToInt32(RouteData.Values["goodId"]);
                Good good = db.GoodSet.Where(x => x.Id == goodId).FirstOrDefault();

                if (good != null)
                {
                    Manufacturer manufacturer = db.ManufacturerSet.Where(x => x.Id == good.Manufacturer.Id).FirstOrDefault();
                    ViewBag.Title = String.Format("Синдика | {0} {1}", manufacturer.Name, good.Name);

                    List<ModificationGood> modificationGoodSet = db.ModificationGoodSet.Where(x => x.Good.Id == good.Id).ToList();
                    GoodView goodItemView = new GoodView(db, modificationGoodSet, null, null);
                    return View("Index", goodItemView);
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Index(int? modificationId, int? PriceId)
        {
            List<ModificationGood> modificationGoodSet = db.ModificationGoodSet.Where(x => x.Id == modificationId).ToList();
            //GoodView goodItemView = new GoodView(db, modificationGoodSet, null);
            return View("Index"/*, goodItemView*/);
        }
    }
}

Bazarkin/Sindika.Web/Views/Good/Index.cshtml
@using Sindika.Web.Models
@model GoodView

@{
//ViewBag.Title = "GoodItem";
}
@Html.Partial("Header")
@Html.Partial("BreadCrumbs")
<div class="w-section">
    <div class="w-container">
        <div class="w-row">
            <div class="w-col w-col-5">
                <div class="w-slider goodslider" data-animation="slide" data-duration="500" data-infinite="1">
                    <div class="w-slider-mask">
                        @if (Model.imageGoodList == null || Model.imageGoodList.Count() == 0)
                        {
                            <div class="w-slide"><img src="~/Content/Images/good/fileNull.jpg" /></div>
                        }
                        else
                        {
                            foreach (var imageGood in Model.imageGoodList)
                            {
                                <div class="w-slide"><img src="~/Content/Images/good/@(imageGood.Name).jpg" /></div>
                            }
                        }
                    </div>
                    @*<div class="w-slider-arrow-left">
                        <div class="w-icon-slider-left"></div>
                    </div>
                    <div class="w-slider-arrow-right">
                        <div class="w-icon-slider-right"></div>
                    </div>*@
                    <div class="w-slider-nav w-round"></div>
                </div>
            </div>
            <div class="w-col w-col-7 w-clearfix">
                <h2>@Model.manufacturer.Name @Model.good.Name</h2>
                @*<div class="goodarlicul">[@Model.good.Id] SM-G920F&nbsp;|&nbsp;SM-G925F</div>*@
                @using (Html.BeginForm("Index","Cart"))
                {
                    foreach (var modificationAndPrice in Model.modificationAndPriceSet)
                    {
                        <div class="goodmodefy">
                            @if (Model.modificationAndPriceSet.Count() > 1)
                            {
                                <div class="goodtext">@modificationAndPrice.modificationString </div>
                                <div class="goodradiobtn">@Html.RadioButton("modificationId", modificationAndPrice.modificationGood.Id)</div>
                            }
                            else
                            {
                                <div class="goodtext"></div>
                                <div class="goodradiobtn"></div>
                            }

                            @if (modificationAndPrice.priceSet != null)
                            {
                                if (modificationAndPrice.priceSet.Count == 1)
                                {
                                    <div class="goodprice">@modificationAndPrice.priceSet.Min(x => x.Value) р</div>
                                }
                                else if (modificationAndPrice.priceSet.Count > 1)
                                {
                                    <div class="goodprice">от @modificationAndPrice.priceSet.Min(x => x.Value) р</div>
                                }
                                else
                                {
                                    <div class="goodprice">нет в продаже</div>
                                }
                            }
                            else
                            {
                                <div class="goodprice">нет в продаже</div>
                            }
                        </div>
                    }
                    <div class="goodbtnlist">
                        <div class="goodbtn">
                            <i class="fa fa-clone fa-fw"></i>
                            <div class="goodbtntext">К сравнению</div>
                        </div>
                        <div class="goodbtn">
                            <i class="fa fa-bookmark-o fa-fw"></i>
                            <div class="goodbtntext">В закладки</div>
                        </div>
                        <div class="goodbtn">
                            <i class="fa fa-share-alt fa-fw"></i>
                            <div class="goodbtntext">Поделиться</div>
                        </div>
                        @*<a class="btn" href="#">Показать</a>*@
                        @if (Model.modificationAndPriceSet.Count() == 1 && Model.modificationAndPriceSet[0].priceSet.Count() == 1)
                        {
                            <input class="btngoodview" type="submit" value="В корзину" />
                        }
                        else if (Model.modificationAndPriceSet.Count() == 1 && Model.modificationAndPriceSet[0].priceSet.Count() > 1)
                        {
                            <input class="btngoodview" type="submit" value="Продавцы" />
                        }
                        else if (Model.modificationAndPriceSet.Count() > 1)
                        {
                            <input class="btngoodview" type="submit" value="Показать" />
                        }

                    </div>
                }
                <div class="gooddescription">@Model.good.Description</div>
            </div>
        </div>
        <div class="w-tabs tabs" data-duration-in="300" data-duration-out="100">
            <div class="w-tab-menu">
                <a class="w-tab-link w--current w-inline-block" data-w-tab="Tab 1">
                    <div>Торговые точки</div>
                </a>
                <a class="w-tab-link w-inline-block" data-w-tab="Tab 2">
                    <div>Характеристики</div>
                </a>
                @*<a class="w-tab-link w-inline-block" data-w-tab="Tab 3">
                        <div>Коментарии</div>
                    </a>*@
            </div>
            <div class="w-tab-content">
                <div class="w-tab-pane w--tab-active" data-w-tab="Tab 1">
                    <div class="w-slider organizationmapslider" data-animation="slide" data-duration="500" data-infinite="1">
                        <div class="lr5">
                            @if (Model.organizationUnitAndPriceList.Count() == 0)
                            {
                                <img src="~/Content/Images/maps/map.jpg" width="100%" />
                            }
                            else if (Model.organizationUnitAndPriceList.Count() > 1)
                            {
                                <img src="~/Content/Images/maps/mapAll.jpg" width="100%" />
                            }
                            else
                            {
                                <img src="~/Content/Images/maps/map@(Model.organizationUnitAndPriceList[0].organizationUnit.Id).jpg" width="100%" />
                            }
                        </div>
                    </div>
                    @{bool flag = true;}
                    @foreach (var organizationUnitAndPrice in Model.organizationUnitAndPriceList)
                    {
                        string strClass1;
                        if (flag)
                        {
                            strClass1 = "w-clearfix goodtochka";
                        }
                        else
                        {
                            strClass1 = "w-clearfix goodtochka gray";
                        }
                        flag = !flag;

                        <div class="@strClass1">
                            @*<div class="goodnumbertochka">@organizationUnitAndPrice.organizationUnit.Id</div>
                                @{string hrefStr = "/org" + organizationUnitAndPrice.organization.Id;}
                                <div class="goodtochkaname"><a href="@hrefStr">@organizationUnitAndPrice.organization.Name</a></div>
                                <div class="w-hidden-main w-hidden-medium w-hidden-tiny w-clearfix goodtochkapriceandbay">
                                    <div class="w-hidden-main w-hidden-medium w-hidden-tiny goodtochkaprice">@organizationUnitAndPrice.priceSet.Min(x=>x.Value) р.</div>
                                    <div class="goodtochkabay">
                                        <div class="w-hidden-main w-hidden-medium w-hidden-tiny">В корзину</div>
                                    </div>
                                </div>
                                <div class="goodtochkadescription">@organizationUnitAndPrice.addressStr</div>
                                <div class="goodtochkaprice visible">@organizationUnitAndPrice.priceSet.Min(x => x.Value) р.</div>
                                <div class="goodtochkabay visible">
                                    <div>
                                        @using (Html.BeginForm())
                                        {
                                            @Html.Hidden("PriceId", organizationUnitAndPrice.priceSet[0].Id)
                                            <input type="submit" value="В корзину" />
                                        }
                                    </div>
                                </div>*@
                            <div class="goodnumbertochka">@organizationUnitAndPrice.organizationUnit.Id</div>
                            @{string hrefStr = "/org" + organizationUnitAndPrice.organization.Id;}
                            <div class="goodtochkaname"><a href="@hrefStr">@organizationUnitAndPrice.organization.Name</a> <span class="textgray">@organizationUnitAndPrice.addressStr</span></div>
                            <div class="goodtochkaprice">@organizationUnitAndPrice.priceSet.Min(x => x.Value) р.</div>
                            @using (Html.BeginForm("Index", "Cart"))
                            {
                                @Html.Hidden("PriceId", organizationUnitAndPrice.priceSet[0].Id)
                                <input class="goodtochkabay" type="submit" value="В корзину" />
                            }
                        </div>
                                }
                </div>
                <div class="w-tab-pane" data-w-tab="Tab 2">
                    @{flag = true;}
                    @foreach (var propertyGroup in Model.propertyGroupAndValueSet)
                    {
                        string strClass2;
                        if (flag)
                        {
                            strClass2 = "goodharakteristikagroup";
                        }
                        else
                        {
                            strClass2 = "goodharakteristikagroup gray";
                        }
                        flag = !flag;
                        <div class="@strClass2">
                            <div class="w-row">
                                <div class="w-col w-col-3 w-clearfix">
                                    <div class="goodharakteristikagroupname">@propertyGroup.propertyGroup.Name</div>
                                </div>
                                <div class="w-col w-col-9 w-clearfix">
                                    @foreach (var propertyAndValue in propertyGroup.propertyAndValueSet)
                                    {
                                        if (propertyAndValue.propertyValueString != string.Empty)
                                        {
                                            <div class="goodharakteristikabox">
                                                <div class="goodharakteristikaname">@propertyAndValue.property.Name</div>
                                                <div class="goodharakteristikavalue">@propertyAndValue.propertyValueString</div>
                                            </div>
                                        }
                                    }
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="w-tab-pane" data-w-tab="Tab 3"></div>
            </div>
        </div>
    </div>
</div>